# Generated by Django 2.1.3 on 2019-02-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenda', '0003_auto_20190205_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='profile',
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
